// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqldb

import (
	"database/sql"
	"time"
)

type Answer struct {
	ID             int32
	AnswerText     string
	QuestionID     int32
	RowInserted    time.Time
	RowLastUpdated sql.NullTime
}

type Question struct {
	ID             int32
	QuestionText   string
	RowInserted    time.Time
	RowLastUpdated sql.NullTime
}
